name: Bazel Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build with Bazel
        run: bazel build //:extension_pkg

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension-package
          path: bazel-bin/extension_pkg.zip